# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc1e1762160ce8bca986b1e87dcf4bb14031e45403c6d664f946c38c3185f710b1736a248459c3ffd70b52ecc3148bea2b38566d96e115aba365324ac1ffd7e

test:
  secret_key_base: 13f7c3cd11cd988757af8204ea4eaf708846ba0a914b3983aac722b2562aab495c3627781d23a41c357753abd9de39788f35e307bc8009026c7d80a647d28f25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
